<a href="https://colab.research.google.com/github/Akshata1992/TensorFlow/blob/master/TF2_0_TextProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [3]:
#import all other libraries
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
#create a dummy data
sentences = ['I like preparing food.',
             'I like to bake cake.',
             'I want to do course on baking.']

In [5]:
MAX_VOCAB_SIZE=20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [6]:
print(sequences)

[[1, 2, 4, 5], [1, 2, 3, 6, 7], [1, 8, 3, 9, 10, 11, 12]]


In [7]:
#Get the word to index mapping
tokenizer.word_index

{'bake': 6,
 'baking': 12,
 'cake': 7,
 'course': 10,
 'do': 9,
 'food': 5,
 'i': 1,
 'like': 2,
 'on': 11,
 'preparing': 4,
 'to': 3,
 'want': 8}

In [8]:
#pad the sequences, use the default
data = pad_sequences(sequences)
print(data)

[[ 0  0  0  1  2  4  5]
 [ 0  0  1  2  3  6  7]
 [ 1  8  3  9 10 11 12]]


In [20]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
data

array([[ 0,  1,  2,  4,  5],
       [ 1,  2,  3,  6,  7],
       [ 3,  9, 10, 11, 12]], dtype=int32)

In [15]:
data = pad_sequences(sequences,maxlen=MAX_SEQUENCE_LENGTH ,padding='pre')
data

array([[ 0,  0,  0,  1,  2,  4,  5],
       [ 0,  0,  1,  2,  3,  6,  7],
       [ 1,  8,  3,  9, 10, 11, 12]], dtype=int32)

In [16]:
data = pad_sequences(sequences,maxlen=MAX_SEQUENCE_LENGTH,padding='post')
data

array([[ 1,  2,  4,  5,  0,  0,  0],
       [ 1,  2,  3,  6,  7,  0,  0],
       [ 1,  8,  3,  9, 10, 11, 12]], dtype=int32)

In [24]:
data = pad_sequences(sequences,maxlen=MAX_SEQUENCE_LENGTH,truncating='pre')
data

array([[ 0,  1,  2,  4,  5],
       [ 1,  2,  3,  6,  7],
       [ 3,  9, 10, 11, 12]], dtype=int32)

In [25]:
data = pad_sequences(sequences,maxlen=MAX_SEQUENCE_LENGTH,truncating='post')
data

array([[ 0,  1,  2,  4,  5],
       [ 1,  2,  3,  6,  7],
       [ 1,  8,  3,  9, 10]], dtype=int32)